"""create core table with PostGIS

Revision ID: 034e6815354f
Revises: 
Create Date: 2026-01-22 13:43:35.042478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '034e6815354f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='User ID (matches Supabase Auth)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Full name'),
    sa.Column('avatar_url', sa.String(), nullable=True, comment='Profile picture URL'),
    sa.Column('bio', sa.String(), nullable=True, comment='User bio'),
    sa.Column('is_premium', sa.Boolean(), nullable=True, comment='Premium subscription status'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Email verification status'),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True, comment='Premium subscription end date'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Account creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update time'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last login time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False, comment='Trip ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Trip title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Trip description'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='Trip start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Trip end date'),
    sa.Column('cover_photo_url', sa.Text(), nullable=True, comment='Cover photo URL'),
    sa.Column('visibility', sa.String(length=20), nullable=True, comment='Visibility: private | unlisted | public'),
    sa.Column('views_count', sa.Integer(), nullable=True, comment='Number of views'),
    sa.Column('saves_count', sa.Integer(), nullable=True, comment='Number of saves'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update time'),
    sa.CheckConstraint("visibility IN ('private', 'unlisted', 'public')", name='check_visibility'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_valid_dates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index(op.f('ix_trips_visibility'), 'trips', ['visibility'], unique=False)
    op.create_table('trip_places',
    sa.Column('id', sa.UUID(), nullable=False, comment='Place ID'),
    sa.Column('trip_id', sa.UUID(), nullable=False, comment='Parent trip ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Place name'),
    sa.Column('place_type', sa.String(length=50), nullable=True, comment='Category: restaurant, hotel, attraction, etc.'),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False, comment='PostGIS Geography point (WGS84)'),
    sa.Column('lat', sa.Float(), nullable=False, comment='Latitude (WGS84)'),
    sa.Column('lng', sa.Float(), nullable=False, comment='Longitude (WGS84)'),
    sa.Column('user_notes', sa.Text(), nullable=True, comment='Personal notes'),
    sa.Column('user_rating', sa.Integer(), nullable=True, comment='Rating 1-5'),
    sa.Column('visit_date', sa.Date(), nullable=True, comment='Date of visit'),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of photo objects: [{url, caption, order}]'),
    sa.Column('videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of video objects: [{url, caption, order}]'),
    sa.Column('external_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Cached data from Foursquare, Mapbox, etc.'),
    sa.Column('order_in_trip', sa.Integer(), nullable=True, comment='Position in trip itinerary'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update time'),
    sa.CheckConstraint('user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)', name='check_rating'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_trip_places_location', 'trip_places', ['location'], unique=False, postgresql_using='gist')
    # Create index only if it doesn't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_trip_places_location
            ON trip_places USING GIST (location)
    """)
    op.create_index(op.f('ix_trip_places_trip_id'), 'trip_places', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_places_trip_id'), table_name='trip_places')
    op.drop_index('idx_trip_places_location', table_name='trip_places', postgresql_using='gist')
    op.drop_table('trip_places')
    op.drop_index(op.f('ix_trips_visibility'), table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
