"""add search index to trip_places

Revision ID: 6cfcf98fd21b
Revises: fc795732477e
Create Date: 2026-01-28 02:19:38.487888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cfcf98fd21b'
down_revision: Union[str, None] = 'fc795732477e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip_places', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of photo media IDs',
               existing_comment='Array of photo objects: [{url, caption, order}]',
               existing_nullable=True)
    
    # 1. Add search_vector column (if not already added by autogenerate)
    op.execute("""
        ALTER TABLE trip_places
        ADD COLUMN IF NOT EXISTS search_vector tsvector;
    """)
    
    # 2. Populate existing data
    op.execute("""
        UPDATE trip_places 
        SET search_vector = to_tsvector('english',
            coalesce(name, '') || ' ' ||
            coalesce(user_notes, '') || ' ' ||
            coalesce(place_type, '')
        )
        WHERE search_vector IS NULL;
    """)
    
    # 3. Create GIN index (ChatGPT caught this missing!)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_trip_places_search
        ON trip_places USING GIN(search_vector);
    """)
    
    # 4. Create trigger function (OR REPLACE for idempotency)
    op.execute("""
        CREATE OR REPLACE FUNCTION trip_places_search_trigger()
        RETURNS trigger AS $$
        BEGIN
          NEW.search_vector := to_tsvector('english',
            coalesce(NEW.name, '') || ' ' ||
            coalesce(NEW.user_notes, '') || ' ' ||
            coalesce(NEW.place_type, '')
          );
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # 5. Create trigger
    op.execute("""
        DROP TRIGGER IF EXISTS tsvector_update ON trip_places;
        CREATE TRIGGER tsvector_update
        BEFORE INSERT OR UPDATE ON trip_places
        FOR EACH ROW EXECUTE FUNCTION trip_places_search_trigger();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip_places', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of photo objects: [{url, caption, order}]',
               existing_comment='Array of photo media IDs',
               existing_nullable=True)
    """Remove full-text search from trip_places."""
    
    # Clean rollback (ChatGPT caught incomplete downgrade!)
    op.execute("DROP TRIGGER IF EXISTS tsvector_update ON trip_places;")
    op.execute("DROP FUNCTION IF EXISTS trip_places_search_trigger();")
    op.execute("DROP INDEX IF EXISTS idx_trip_places_search;")
    op.execute("ALTER TABLE trip_places DROP COLUMN IF EXISTS search_vector;")
    # ### end Alembic commands ###
