"""create media_files table

Revision ID: fc795732477e
Revises: 034e6815354f
Create Date: 2026-01-26 04:20:35.085869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc795732477e'
down_revision: Union[str, None] = '034e6815354f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False, comment='Media file ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('trip_place_id', sa.UUID(), nullable=False, comment='Associated place ID'),
    sa.Column('file_url', sa.Text(), nullable=False, comment='Full URL to file in Supabase Storage'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='Type: photo or video'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME type (image/jpeg, image/png, video/mp4, etc.)'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Height in pixels'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='URL to thumbnail (for photos)'),
    sa.Column('caption', sa.Text(), nullable=True, comment='User-provided caption'),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True, comment='When photo/video was taken'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When record was created'),
    sa.ForeignKeyConstraint(['trip_place_id'], ['trip_places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_trip_place_id'), 'media_files', ['trip_place_id'], unique=False)
    op.create_index(op.f('ix_media_files_user_id'), 'media_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_user_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_trip_place_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
