"""add advisory pipeline tables

Revision ID: ffd82b6d69e4
Revises: 1c3f9e8a7b2d
Create Date: 2026-04-15 00:07:31.950735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd82b6d69e4'
down_revision: Union[str, None] = '1c3f9e8a7b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Advisory job ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('trip_id', sa.UUID(), nullable=False, comment='Target trip ID'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='queued|processing|cancel_requested|completed|failed|canceled|blocked'),
    sa.Column('stage', sa.String(length=32), nullable=True, comment='Current pipeline stage'),
    sa.Column('progress', sa.Float(), nullable=False, comment='Progress 0.0..1.0'),
    sa.Column('job_type', sa.String(length=32), nullable=False, comment='pre_trip|on_demand|location_trigger'),
    sa.Column('request_hash', sa.String(length=64), nullable=False, comment='SHA-256 of (job_type, normalized_query) for idempotency'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Raw NL query for on_demand jobs'),
    sa.Column('parsed_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM-parsed intent from query_text (populated by worker)'),
    sa.Column('scrape_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Orchestrator output: seeds, keywords, extraction instructions'),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Intermediate results accumulated across stages'),
    sa.Column('error_code', sa.String(length=64), nullable=True, comment='Structured error code'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Human-readable error'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Attempt count'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Max retry attempts'),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True, comment='Retry eligibility time'),
    sa.Column('worker_session_id', sa.String(length=64), nullable=True, comment='Current worker session'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Worker claim time'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Terminal time'),
    sa.CheckConstraint("job_type IN ('pre_trip', 'on_demand', 'location_trigger')", name='check_advisory_job_type'),
    sa.CheckConstraint("stage IS NULL OR stage IN ('route_segmentation', 'reddit_scrape', 'tripadvisor_scrape', 'gmaps_scrape', 'llm_extraction', 'scoring', 'delivery')", name='check_advisory_job_stage'),
    sa.CheckConstraint("status IN ('queued', 'processing', 'cancel_requested', 'completed', 'failed', 'canceled', 'blocked')", name='check_advisory_job_status'),
    sa.CheckConstraint('max_retries >= 0', name='check_advisory_job_max_retries_non_negative'),
    sa.CheckConstraint('progress >= 0.0 AND progress <= 1.0', name='check_advisory_job_progress_range'),
    sa.CheckConstraint('retry_count >= 0', name='check_advisory_job_retry_non_negative'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_advisory_jobs_status_next_attempt', 'advisory_jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_index('idx_advisory_jobs_trip', 'advisory_jobs', ['trip_id'], unique=False)
    op.create_index('idx_advisory_jobs_user_status', 'advisory_jobs', ['user_id', 'status'], unique=False)
    op.create_index('uq_advisory_jobs_active_per_trip', 'advisory_jobs', ['trip_id', 'job_type', 'request_hash'], unique=True, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.create_table('trip_advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('advisory_job_id', sa.UUID(), nullable=True, comment='Job that produced this advisory'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='Insight category'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='reddit|tripadvisor|google_maps|combined'),
    sa.Column('place_name', sa.Text(), nullable=True, comment='Specific place/area name'),
    sa.Column('place_lat', sa.Float(), nullable=True),
    sa.Column('place_lng', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('context_signal', sa.Text(), nullable=True, comment="e.g. '3 Reddit users agreed'"),
    sa.Column('best_for', sa.Text(), nullable=True, comment="e.g. 'solo female travelers'"),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_urls', postgresql.ARRAY(sa.Text()), nullable=True, comment='Source page URLs'),
    sa.Column('source_count', sa.Integer(), nullable=False, comment='Corroborating source count'),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False, comment='SHA-256 hash of (place_name, category, body[:100])'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Delivery-only: pending|delivered|expired'),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True, comment='When source data was scraped'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('safety_warning', 'scam_alert', 'food_tip', 'photo_spot', 'transport_tip', 'accommodation', 'cultural_etiquette', 'must_do', 'avoid', 'general_tip')", name='check_advisory_category'),
    sa.CheckConstraint("source IN ('reddit', 'tripadvisor', 'google_maps', 'combined')", name='check_advisory_source'),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'expired')", name='check_advisory_status'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_advisory_confidence_range'),
    sa.ForeignKeyConstraint(['advisory_job_id'], ['advisory_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'dedupe_key', name='uq_advisory_trip_dedupe')
    )
    op.create_index('idx_advisory_job', 'trip_advisories', ['advisory_job_id'], unique=False)
    op.create_index('idx_advisory_trip_status', 'trip_advisories', ['trip_id', 'status'], unique=False)
    op.create_index('idx_advisory_user_category', 'trip_advisories', ['user_id', 'category'], unique=False)
    op.create_table('advisory_user_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('advisory_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False, comment='dismissed|liked|saved|acted_on|converted_to_place'),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra context, e.g. which place the user saved it to'),
    sa.Column('trip_metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of TripMetadata at action time for similarity matching'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('dismissed', 'liked', 'saved', 'acted_on', 'converted_to_place')", name='check_advisory_action_type'),
    sa.ForeignKeyConstraint(['advisory_id'], ['trip_advisories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_advisory_action_advisory', 'advisory_user_actions', ['advisory_id'], unique=False)
    op.create_index('idx_advisory_action_trip', 'advisory_user_actions', ['trip_id'], unique=False)
    op.create_index('idx_advisory_action_user', 'advisory_user_actions', ['user_id', 'action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'v2_backend_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether strict V2 ingest/projection backend lane is enabled for this trip',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trip_tracking_sessions', 'device_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Device context metadata for diagnostics and policy',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_tracking_sessions', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='IANA timezone',
               existing_nullable=True)
    op.alter_column('trip_tracking_sessions', 'last_point_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Latest ingested point timestamp',
               existing_nullable=True)
    op.alter_column('trip_tracking_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Type-specific metadata payload',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_tracking_events', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Original capture timestamp',
               existing_nullable=False)
    op.alter_column('trip_tracking_events', 'event_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='note|warn|tag|photo|media',
               existing_nullable=False)
    op.alter_column('trip_tracking_events', 'client_event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Client-generated idempotent event identity',
               existing_nullable=False)
    op.alter_column('trip_tracking_events', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Optional tracking session ID',
               existing_nullable=True)
    op.alter_column('trip_tracking_events', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_events', 'trip_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Parent trip ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_events', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tracking event ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional media metadata payload',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_tracking_event_media', 'upload_ref',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Opaque upload/file reference from client',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'anchor_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Route anchor longitude for route-mode',
               existing_nullable=True)
    op.alter_column('trip_tracking_event_media', 'anchor_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Route anchor latitude for route-mode',
               existing_nullable=True)
    op.alter_column('trip_tracking_event_media', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Original media capture timestamp',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'trip_place_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bound trip place for place-mode media',
               existing_nullable=True)
    op.alter_column('trip_tracking_event_media', 'bind_mode',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='place|route',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'media_type',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='photo|media',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'client_event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Client-generated event identity this media belongs to',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'client_media_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Client-generated idempotent media identity',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owning tracking event row ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'trip_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Parent trip ID',
               existing_nullable=False)
    op.alter_column('trip_tracking_event_media', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Media row ID',
               existing_nullable=False)
    op.alter_column('trip_places', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               comment=None,
               existing_comment='Full-text search vector (auto-updated by trigger)',
               existing_nullable=True)
    op.alter_column('trip_places', 'candidate_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Origin check-in candidate for auto-generated places',
               existing_nullable=True)
    op.alter_column('trip_places', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Inference confidence for auto/edited_auto places',
               existing_nullable=True)
    op.alter_column('trip_moments', 'locked_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Manual lock markers for auto-updatable fields',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_moments', 'extra_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata payload for inference/debug',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_moments', 'media_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of related media references',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('trip_moments', 'captured_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Original capture timestamp',
               existing_nullable=False)
    op.alter_column('trip_moments', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Inference confidence for auto moments',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'provider',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='gps|network|fused|unknown',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'altitude_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Altitude in meters',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'heading_deg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Heading in degrees',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'speed_mps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Speed in m/s',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'accuracy_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Horizontal accuracy in meters',
               existing_nullable=True)
    op.alter_column('trip_location_points', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='WGS84 longitude',
               existing_nullable=False)
    op.alter_column('trip_location_points', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='WGS84 latitude',
               existing_nullable=False)
    op.alter_column('trip_compiled_route_segments', 'geometry',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='GeoJSON-like route payload',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_compiled_route_segments', 'segment_key',
               existing_type=sa.VARCHAR(length=160),
               comment=None,
               existing_comment='Deterministic segment identity',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_state', 'stale',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when latest compile attempt failed and last good snapshot is served',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('trip_compiled_projection_state', 'dirty',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when projection should be recomputed',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('trip_compiled_projection_state', 'compiler_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Projection compiler contract version',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('trip_compiled_projection_state', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner user ID',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_state', 'trip_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Trip ID',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_overrides', 'action',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='bind|unbind',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_overrides', 'source_kind',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='tracking_event|tracking_event_media',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_items', 'bind_source',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='auto|manual|none',
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('trip_compiled_projection_items', 'bucket_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='place|on_route',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_items', 'event_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='note|warn|tag|photo|media',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_items', 'source_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Source row UUID',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_items', 'source_kind',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='tracking_event|tracking_event_media',
               existing_nullable=False)
    op.alter_column('trip_compiled_projection_items', 'entry_id',
               existing_type=sa.VARCHAR(length=160),
               comment=None,
               existing_comment='Deterministic projection entry identity',
               existing_nullable=False)
    op.alter_column('trip_checkin_candidates', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Candidate feature payload used by scoring/inference',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('trip_checkin_candidates', 'confirmed_trip_place_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Chosen place after user confirmation',
               existing_nullable=True)
    op.alter_column('trip_checkin_candidates', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Inferred stay end time',
               existing_nullable=True)
    op.alter_column('trip_checkin_candidates', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Inferred stay start time',
               existing_nullable=True)
    op.alter_column('trip_checkin_candidates', 'suggested_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Suggested longitude',
               existing_nullable=True)
    op.alter_column('trip_checkin_candidates', 'suggested_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Suggested latitude',
               existing_nullable=True)
    op.alter_column('trip_checkin_candidates', 'suggested_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Suggested place name',
               existing_nullable=True)
    op.alter_column('trip_auto_entity_tombstones', 'reason',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Deletion reason',
               existing_nullable=True)
    op.alter_column('trip_auto_entity_tombstones', 'cooldown_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Suppression expiry',
               existing_nullable=False)
    op.alter_column('trip_auto_entity_tombstones', 'deleted_entity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Original entity ID if available',
               existing_nullable=True)
    op.alter_column('trip_auto_entity_tombstones', 'entity_fingerprint',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Fingerprint used to suppress regeneration',
               existing_nullable=False)
    op.alter_column('search_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When search occurred',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_events', 'results_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of results returned',
               existing_nullable=True)
    op.alter_column('search_events', 'radius_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Search radius in kilometers',
               existing_nullable=True)
    op.alter_column('search_events', 'lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Search center longitude',
               existing_nullable=True)
    op.alter_column('search_events', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Search center latitude',
               existing_nullable=True)
    op.alter_column('search_events', 'query',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Search query text (normalized)',
               existing_nullable=False)
    op.alter_column('search_events', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who performed search',
               existing_nullable=True)
    op.alter_column('search_events', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('routes', 'inferred_from_session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tracking session that generated this inferred route',
               existing_nullable=True)
    op.alter_column('routes', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Inference confidence for auto/edited_auto routes',
               existing_nullable=True)
    op.alter_column('place_views', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When view occurred',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('place_views', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Result source: local, foursquare, etc.',
               existing_nullable=True)
    op.alter_column('place_views', 'place_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Place that was viewed (null for external)',
               existing_nullable=True)
    op.alter_column('place_views', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who viewed place',
               existing_nullable=True)
    op.alter_column('place_views', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('place_saves', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When save occurred',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('place_saves', 'place_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Place that was saved',
               existing_nullable=True)
    op.alter_column('place_saves', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who saved place',
               existing_nullable=True)
    op.alter_column('place_saves', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('export_share_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Revocation timestamp',
               existing_nullable=True)
    op.alter_column('export_share_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Share token expiry timestamp',
               existing_nullable=False)
    op.alter_column('export_jobs', 'render_duration_ms',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Total render duration in milliseconds',
               existing_nullable=True)
    op.alter_column('export_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Terminal completion time',
               existing_nullable=True)
    op.alter_column('export_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Worker claim time',
               existing_nullable=True)
    op.alter_column('export_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('export_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_idempotency_records', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='TTL cutoff for idempotency record',
               existing_nullable=False)
    op.alter_column('api_idempotency_records', 'replay_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Replay hit counter',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('api_idempotency_records', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Original response payload for replay',
               existing_nullable=True)
    op.alter_column('api_idempotency_records', 'response_status',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Original HTTP response status',
               existing_nullable=False)
    op.alter_column('api_idempotency_records', 'request_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Hash of normalized request payload',
               existing_nullable=False)
    op.alter_column('api_idempotency_records', 'idempotency_key',
               existing_type=sa.VARCHAR(length=96),
               comment=None,
               existing_comment='Client idempotency key',
               existing_nullable=False)
    op.alter_column('api_idempotency_records', 'endpoint_signature',
               existing_type=sa.VARCHAR(length=160),
               comment=None,
               existing_comment='Normalized endpoint + method signature',
               existing_nullable=False)
    op.drop_index('idx_advisory_action_user', table_name='advisory_user_actions')
    op.drop_index('idx_advisory_action_trip', table_name='advisory_user_actions')
    op.drop_index('idx_advisory_action_advisory', table_name='advisory_user_actions')
    op.drop_table('advisory_user_actions')
    op.drop_index('idx_advisory_user_category', table_name='trip_advisories')
    op.drop_index('idx_advisory_trip_status', table_name='trip_advisories')
    op.drop_index('idx_advisory_job', table_name='trip_advisories')
    op.drop_table('trip_advisories')
    op.drop_index('uq_advisory_jobs_active_per_trip', table_name='advisory_jobs', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index('idx_advisory_jobs_user_status', table_name='advisory_jobs')
    op.drop_index('idx_advisory_jobs_trip', table_name='advisory_jobs')
    op.drop_index('idx_advisory_jobs_status_next_attempt', table_name='advisory_jobs')
    op.drop_table('advisory_jobs')
    # ### end Alembic commands ###
